kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands: 
      - echo $${USERNAME}
      - echo $${PASSWORD}
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: secret
name: docker_username
get:
  path: secret/data/docker
  name: username

---
kind: secret
name: docker_password
get:
  path: secret/data/docker
  name: password
