kind: pipeline
name: default

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: ow.serg.pl
    username:
      from_secret: myname
    password:
      from_secret: docker_password
    script:
      - echo hello
      - echo world
      
- name: build
  image: node:latest
  commands: 
      - echo $${tr1}
      - echo $${tr2}
      - echo $${tr3}
      - echo $${HOST}
  environment:
      tr1: 
        from_secret: docker_password
      tr2:
        from_secret: myname
      tr3: sssss

      
---
kind: secret
name: myname
get:
  path: docker/data/docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker/data/docker
  name: password
