kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands: 
      - echo $${tr1}
      - echo $${tr2}
      - echo $${tr3}
  environment:
      tr1: 
        from_secret: docker_password
      tr2:
        from_secret: docker_username
      tr3: sssss

      
---
kind: secret
name: docker_username
get:
  path: docker/data/docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker/data/docker
  name: password
