pipeline:
  build:
    image: node:latest
    commands: npm install
  test:
    image: node:latest
    commands: npm run test

secret:
  docker_username:
     path: secret/docker_username
  docker_password:
     path: secret/docker_password 
